apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  database: "demo_db"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
data:
  index.html: |
    <html>
    <head><title>Welcome</title></head>
    <body><h1>Hello and welcome to the ultimate Altice Labs Kubernetes exercise!</h1></body>
    </html>