apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: nginx
          # Adding environment variable from ConfigMap
          env:
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: ENV
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: my-app-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: my-app-secret
                  key: DB_PASS
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/app/data"
              name: storage-volume
      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: missing-pvc  # Ensure this PVC exists in your cluster