apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo-container
          image: busybox
          command: ["/bin/sh", "-c", "while true; do echo Hello from $(hostname); sleep 5; done"]

